---
title: "P8105 Homework 5"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(httr)
```


## Problem 1: Longitudinal Study 

```{r longstudy_df, message = FALSE}
# Create a dataframe containing file names.
# Input for extracting file data
longstudy_filenames = 
  tibble(subject = list.files("data")) %>% 
  mutate(subject = str_c("./data/", subject))

# Iterate over filenames and read in data into one dataframe
longstudy_df = 
  longstudy_filenames %>% 
  mutate(subject_data = map(.x = subject, ~read_csv(.x))) %>% 
  unnest()

# Clean and tidy dataset
# Separate filename in subject to only contain subjectID
# Group subjectIDs by individuals administered control or experimental arm
longstudy_df = longstudy_df %>% 
  separate(subject, into = c("remove1", "subjectID"), sep = "a/") %>% 
  separate(subjectID, into = c("subjectID", "remove2"), sep = ".c") %>%
  mutate(subject_ID = subjectID) %>% 
  separate(subjectID, into = c("subject_group", "subject_ID2"), sep = "_") %>% 
  select(subject_group, subject_ID, week_1:week_8) %>% 
  mutate(subject_group = recode(subject_group, 
                                con = "control", 
                                exp = "experimental"))

# Tidy weekly observations by gathering weekly observations
longstudy_df = longstudy_df %>% 
  gather(key = week, value = value, week_1:week_8) %>% 
  separate(week, into = c("remove1", "week"), sep = "_") %>% 
  select(subject_group, subject_ID, week, value) %>% 
  mutate(week = as.numeric(week))
  
longstudy_df
```

#### Spaghetti plot: Observations over time

```{r plot1}
# Create a spaghetti plot showing observations of each subject over time
longstudy_df %>% 
  ggplot(aes(x = week, y = value, group = subject_ID, color = subject_group)) + 
  geom_line() + 
  labs(
    title = "Observations of control vs. experimental groups over weeks", 
    x = "Week", 
    y = "Value"
  ) + 
  theme_bw()
```


## Problem 2: Washington Post Homicide Dataset

```{r homicide_df, mesage = FALSE}
# Pull dataset from web and convert it to readable format in R
# Create city_state variable that combines city and state
homicide_df = read_csv(url("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")) %>% 
    unite(city_state, city:state, sep = ", ") 

```

```{r}
# Summarize total number of homicides by city
homicide_df %>% 
  group_by(city_state) %>% 
  summarize(total_homicides = n())

# Summarize total number of unsolved homicides by city
homicide_df %>% 
  filter(disposition %in% c("Closed without arrest", "Open/No arrest")) %>% 
  group_by(city_state) %>% 
  summarize(unsolved_homicides = n())
```


